spring:
  # 多数据源
  datasource:
    dynamic:
      primary: bonfire
      strict: false
      datasource:
        bonfire:
          driver-class-name: oracle.jdbc.OracleDriver
          url: jdbc:oracle:thin:@144.52.16.141:1521:orcl
          username: BONFIRE
          password: BONFIRE
        lamp:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://144.52.16.141:3306/lamp?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
          username: root
          password: 123456
  # redis
  redis:
    host: 144.52.16.143
    password: foobared
    # 启用连接池
    lettuce:
      pool:
        max-active: 8

# 工程自定义参数
bonfire:
  # 登录是否启用验证码校验
  captchaEnabled: false
  # 默认密码
  defaultPassword: Password666
  uploadPath: /Users/sunhz/Developer/Temp
  tempPath: /Users/sunhz/Developer/Temp